### PR TITLE
Fixes #89

### LINKED ISSUE #89: Arrival Amplitude Calculation raises error
Hello,

My Specs:

Windows10 Python 3.11
arlpy version: 1.8.3
Acoustic Toolbox: Windows binaries updated 20201102

I received the following error when calling compute_arrivals() on the default 2D environment.

```
[DEBUG] Model: bellhop
Traceback (most recent call last):
  File "c:\Users\James\Documents\Testing\arlpy\test.py", line 10, in <module>
    arrivals = pm.compute_arrivals(env, debug=True)
  File "C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\arlpy\uwapm.py", line 325, in compute_arrivals
    return model.run(env, arrivals, debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\arlpy\uwapm.py", line 607, in run
    results = taskmap[task][1](fname_base)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\arlpy\uwapm.py", line 793, in _load_arrivals
    'arrival_amplitude': [data[0] * _np.exp( -1j * (_np.deg2rad(data[1]) + freq * 2 * _np.pi * (data[3] * 1j +  data[2])))],
                                                                           ~~~~~~~~~^~~~~~~~
TypeError: can't multiply sequence by non-int of type 'float'
```

I opened the source file uwapm.py and uncommented the line above where the error occurs and commented the line raising the error as shown here:

```p
'arrival_amplitude': [data[0]*_np.exp(1j * data[1]* _np.pi/180)],
#'arrival_amplitude': [data[0] * _np.exp( -1j * (_np.deg2rad(data[1]) + freq * 2 * _np.pi * (data[3] * 1j +  data[2])))],
```

This resolves the error and produces the arrivals expected from the Bellhop notebook example it seems that the freq variable is a string based on the TypeError.

### PR DESCRIPTION
**Pull request by patel999jay**
Fixes arrival amplitude calculations

### CODE REVIEW

**Comment by mchitre** [comment]
Would it make sense to check if it's a tuple before extracting the entry? That will allow the same code to work on older and newer versions of Bellhop perhaps?

**Comment by patel999jay** [comment]
Which versions should we verify? I currently possess binaries for 2019, 2020, and 2023 versions. I suspect there may be older versions, possibly from 2016. Do you happen to have the binary for that year? I intend to conduct compatibility checks across all these versions.

**Comment by mchitre** [comment]
That's fantastic if you can check across these versions. I think it's sufficient to support these ones, and not bother going much further in history.

**Comment by patel999jay** [comment]
**Compatibility Testing**

I've thoroughly tested this code against multiple versions of Bellhop, including 2016, 2019, 2020, and 2023. The code has been updated to ensure compatibility with these versions, and I've confirmed that it functions as expected without any issues. I've also documented the results in a test notebook PDF, which I attach for further review.

This ensures that the fix not only resolves the issue at hand but also maintains compatibility across a range of Bellhop versions, making it a robust and reliable solution.

Please feel free to reach out if you have any additional questions or need more information regarding the compatibility testing.

[Test1-2016_exe - Jupyter Notebook.pdf](https://github.com/org-arl/arlpy/files/13210449/Test1-2016_exe.-.Jupyter.Notebook.pdf)
[Test3-2019_exe - Jupyter Notebook.pdf](https://github.com/org-arl/arlpy/files/13210450/Test3-2019_exe.-.Jupyter.Notebook.pdf)
[Test4-2020_exe - Jupyter Notebook.pdf](https://github.com/org-arl/arlpy/files/13210452/Test4-2020_exe.-.Jupyter.Notebook.pdf)
[Test5-2023_exe - Jupyter Notebook.pdf](https://github.com/org-arl/arlpy/files/13210453/Test5-2023_exe.-.Jupyter.Notebook.pdf)

**Comment by mchitre** [comment]
Released 1.8.4 with this in it.

**Pull request merged**
