### PR TITLE
feat(plot): added return values to most of the plot.<type> methods to…

### PR DESCRIPTION
**Pull request by notthetup**
… enable live updating of plots

Returns the `GlyphRenderer ` for each of the types of plots, which can then be used for live changing the plot in real time.

For `plot.freqz`, a tuple of `GlyphRenderer`s is returned. One for each of the amplitude and phase plots

### CODE REVIEW

**Comment by mchitre** [comment]
The problem with returning the plot is that the user has to put a ";" at the end to avoid printing out what is returned.

The current mechanism is to use `gcf()` to get the handle to the last figure, so that you can use it to change plot in real-time if needed. Does this not work for your use case?

**Comment by notthetup** [comment]
Unfortunately, I couldn't find a way to get handles to the `GlyphRenderer` from a `Figure` object.

**Comment by mchitre** [comment]
Fair enough. Would it work if we had a similar call as `gcf()` which returned the `GlyphRenderer`? For example `gca()` to match up with MATLAB's equivalent call.

**Comment by notthetup** [comment]
That's what I was thinking about. Potentially have `gcf` return an object which has access to both a list of all `GlyphRenderer` and the `Figure` too.

**Comment by mchitre** [comment]
To avoid breaking existing code, perhaps better to go with a new function or something like `gcf(renderer=True)`.

**Pull request closed without merging**
